### ISSUE TITLE
Refactore codebase

### ISSUE THREAD

**Issue by PrathyushaLakkireddy** [vitwit/cada#18]
- [ ] Remove dead code #44 
- [ ] Change file structure and fix the imports  accordingly #44 
- [ ] Change tests accordingly #44 
- [ ] Rename binary name availd to cada #44
