### ISSUE TITLE
Add interfaces by decoupling code

### ISSUE THREAD

**Issue by PrathyushaLakkireddy** [vitwit/cada#29]
- [x] light client query ref: #41 
- [x] light client data submission ref: #41 
- [x] cosmos local provider ref: #36 
- [x] Tests #47
